name: squid-ci

instance_groups:
- name: squid
  instances: 1
  azs:       [z1]
  vm_type:   default
  stemcell:  default
  networks:
    - name: default
  jobs:
    - name: squid
      release: squid

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: squid
  version: latest
