---
meta:
  name:    squid
  release: Squid Proxy
  target:  pipes
  url:     https://pipes.starkandwayne.com

  manifest:
    path: ci/manifest.yml

  git:
    email: ci@starkandwayne.com
    name:  Stark & Wayne CI Bot


  bosh-lite:
    target: https://10.200.131.9:25555
    username: ((thunder-dome.username))
    password: ((thunder-dome.password))
    cacert:   ((thunder-dome.ca-certificate))

  aws:
    access_key: ((cfcommunity.access))
    secret_key: ((cfcommunity.secret))

  github:
    owner:  cloudfoundry-community
    repo:   squid-boshrelease
    branch: master
    private_key:  ((github.private-key))
    access_token: ((github.access-token))

  slack:
    webhook: ((slack.webhook))
    channel: '#botspam'
    username:      starkandwayne-ci
    icon:          https://www.starkandwayne.com/assets/images/shield-blue-50x50.png
