---
meta:
  name:    squid
  release: Squid Proxy
  target:  sw
  url:     https://ci.starkandwayne.com

  manifest:
    path: ci/manifest.yml

  git:
    email: ci@starkandwayne.com
    name:  Stark & Wayne CI Bot


  bosh-lite:
    target: https://10.58.111.44:25555
    username: (( vault "secret/bosh-lites/lite44/users/admin:username" ))
    password: (( vault "secret/bosh-lites/lite44/users/admin:password" ))
    cacert:   (( vault "secret/bosh-lites/lite44/certs:rootCA.pem" ))

  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))

  github:
    owner:  cloudfoundry-community
    repo:   squid-boshrelease
    branch: master
    private_key:  (( vault "secret/pipelines/shared/github:private_key" ))
    access_token: (( vault "secret/pipelines/shared/github:access_token" ))

  slack:
    webhook: (( vault "secret/pipelines/squid-boshrelease/slack:webhook" ))
    channel: '#botspam'
    username:      starkandwayne-ci
    icon:          https://www.starkandwayne.com/assets/images/shield-blue-50x50.png
